#define CORRECT_DATE_SIZE 10
#define DAY_OR_MONTH_SIZE 2
#define YEAR_SIZE 4
#define MAX_DAY 31
#define MAX_MONTH 12
#define JAN_MAR_MAY_JULY_AUG_OCT_DEC_MAX_DAY 31
#define APR_JUNE_SEPT_NOV_MAX_DAY 30
#define FEB_MAX_DAY 29
#define JANUARY 1
#define FEBRUARY 2
#define MARCH 3
#define APRIL 4
#define MAY 5
#define JUNE 6
#define JULY 7
#define AUGUST 8
#define SEPTEMBER 9
#define OCTOBER 10
#define NOVEMBER 11
#define DECEMBER 12